const listaAlunos = [
  {
    codigo: 1,
    cpf: "000.000.000-00",
    nome: "Eduardo Rossetti",
    dtNascimento: "2023-01-15",
    nomeMae: "Maria da Silva",
    rg: "XXXXXXXX-X",
    endereco: "Rua X",
    bairro: "Vila Y",
    cidade: "ZZZZ",
    uf: "SP",
    tel: "(11)XXXX-XXXX",
    escola: "Escola ZZZZ",
    serie: "5 ano",
    periodo: "Matutino",
  },
  {
    codigo: 2,
    cpf: "000.000.000-00",
    nome: "Cristiano do Couto",
    dtNascimento: "2023-01-15",
    nomeMae: "Lucia de Almeida",
    rg: "XXXXXXXX-X",
    endereco: "Rua X",
    bairro: "Vila Y",
    cidade: "ZZZZ",
    uf: "SP",
    tel: "(11)XXXX-XXXX",
    escola: "Escola ZZZZ",
    serie: "1 ano",
    periodo: "Matutino",
  },
  {
    codigo: 3,
    cpf: "000.000.000-00",
    nome: "Vinicius Alves",
    dtNascimento: "2023-01-15",
    nomeMae: "Solange Lima",
    rg: "XXXXXXXX-X",
    endereco: "Rua X",
    bairro: "Vila Y",
    cidade: "ZZZZ",
    uf: "SP",
    tel: "(11)XXXX-XXXX",
    escola: "Escola ZZZZ",
    serie: "9 ano",
    periodo: "Matutino",
  },
  {
    codigo: 4,
    cpf: "000.000.000-00",
    nome: "José Rodrigues",
    dtNascimento: "2023-01-15",
    nomeMae: "Solange Santos",
    rg: "XXXXXXXX-X",
    endereco: "Rua X",
    bairro: "Vila Y",
    cidade: "ZZZZ",
    uf: "SP",
    tel: "(11)XXXX-XXXX",
    escola: "Escola ZZZZ",
    serie: "8 ano",
    periodo: "Matutino",
  },
  {
    codigo: 5,
    cpf: "000.000.000-00",
    nome: "João da Silva",
    dtNascimento: "2023-01-15",
    nomeMae: "Solange Santos",
    rg: "XXXXXXXX-X",
    endereco: "Rua X",
    bairro: "Vila Y",
    cidade: "ZZZZ",
    uf: "SP",
    tel: "(11)XXXX-XXXX",
    escola: "Escola ZZZZ",
    serie: "8 ano",
    periodo: "Matutino",
  },
  {
    codigo: 6,
    cpf: "000.000.000-00",
    nome: "Luciano Pereira",
    dtNascimento: "2023-01-15",
    nomeMae: "Solange Santos",
    rg: "XXXXXXXX-X",
    endereco: "Rua X",
    bairro: "Vila Y",
    cidade: "ZZZZ",
    uf: "SP",
    tel: "(11)XXXX-XXXX",
    escola: "Escola ZZZZ",
    serie: "8 ano",
    periodo: "Matutino",
  },
];

export default listaAlunos;
