export const LISTA_ALUNOS = [
  {
    codigo: 1,
    cpf: "000.000.000-11",
    nome: "Eduardo Rossetti",
    dtNascimento: "2023-01-15",
    nomeMae: "Maria da Silva",
    rg: "XXXXXXXX-X",
    endereco: "Rua X",
    bairro: "Vila Y",
    cidade: "ZZZZ",
    uf: "SP",
    tel: "(11)XXXX-XXXX",
    escola: "Escola ZZZZ",
    serie: "5 ano",
    periodo: "Matutino",
  },
  {
    codigo: 2,
    cpf: "000.000.000-22",
    nome: "Cristiano do Couto",
    dtNascimento: "2023-01-15",
    nomeMae: "Lucia de Almeida",
    rg: "XXXXXXXX-X",
    endereco: "Rua X",
    bairro: "Vila Y",
    cidade: "ZZZZ",
    uf: "SP",
    tel: "(11)XXXX-XXXX",
    escola: "Escola ZZZZ",
    serie: "1 ano",
    periodo: "Matutino",
  },
  {
    codigo: 3,
    cpf: "000.000.000-33",
    nome: "Vinicius Alves",
    dtNascimento: "2023-01-15",
    nomeMae: "Solange Lima",
    rg: "XXXXXXXX-X",
    endereco: "Rua X",
    bairro: "Vila Y",
    cidade: "ZZZZ",
    uf: "SP",
    tel: "(11)XXXX-XXXX",
    escola: "Escola ZZZZ",
    serie: "9 ano",
    periodo: "Matutino",
  },
  {
    codigo: 4,
    cpf: "000.000.000-44",
    nome: "José Rodrigues",
    dtNascimento: "2023-01-15",
    nomeMae: "Solange Santos",
    rg: "XXXXXXXX-X",
    endereco: "Rua X",
    bairro: "Vila Y",
    cidade: "ZZZZ",
    uf: "SP",
    tel: "(11)XXXX-XXXX",
    escola: "Escola ZZZZ",
    serie: "8 ano",
    periodo: "Matutino",
  },
  {
    codigo: 5,
    cpf: "000.000.000-55",
    nome: "João da Silva",
    dtNascimento: "2023-01-15",
    nomeMae: "Solange Santos",
    rg: "XXXXXXXX-X",
    endereco: "Rua X",
    bairro: "Vila Y",
    cidade: "ZZZZ",
    uf: "SP",
    tel: "(11)XXXX-XXXX",
    escola: "Escola ZZZZ",
    serie: "8 ano",
    periodo: "Matutino",
  },
  {
    codigo: 6,
    cpf: "000.000.000-66",
    nome: "Luciano Pereira",
    dtNascimento: "2023-01-15",
    nomeMae: "Solange Santos",
    rg: "XXXXXXXX-X",
    endereco: "Rua X",
    bairro: "Vila Y",
    cidade: "ZZZZ",
    uf: "SP",
    tel: "(11)XXXX-XXXX",
    escola: "Escola ZZZZ",
    serie: "8 ano",
    periodo: "Matutino",
  },
];

export const LISTA_CARGOS = [
  {
    codigo: 1,
    nome: "Professores",
    descricao:
      "Cargo responsável pela atribuição de frequência dos alunos, além da docência que lhe é própria dentro da instituição",
  },
  {
    codigo: 2,
    nome: "Orientador",
    descricao:
      "Cargo responsável por registrar os relatórios dos aprendizes nas empresas",
  },
  {
    codigo: 3,
    nome: "Administrativo",
    descricao:
      "Cargo responsável pela matrícula do aluno e inserção nas turmas, e cadastros básicos",
  },
];

export const LISTA_CURSOS = [
  {
    codigo: 1,
    nome: "Auxiliar em Manutenção e Montagem de Computadores",
    sala: "Sala 1, Térreo",
    eixo: "N/A",
    cargaHoras: "150 horas",
    professor: "Hannah Arendt",
    dtCriacao: "2023-01-15",
    dtDesativacao: "",
  },
  {
    codigo: 2,
    nome: "Auxiliar de Cozinha",
    sala: "Sala 3, Piso superior",
    eixo: "N/A",
    cargaHoras: "150 horas",
    professor: "Marie Curie",
    dtCriacao: "2023-01-15",
    dtDesativacao: "",
  },
  {
    codigo: 3,
    nome: "Atendente de Telemarketing",
    sala: "Sala 5, Térreo",
    eixo: "N/A",
    cargaHoras: "150 horas",
    professor: "Isaac Newton",
    dtCriacao: "2023-01-15",
    dtDesativacao: "",
  },
];

export const LISTA_EMPRESAS = [
  {
    codigo: 1,
    cnpj: "11.111.111/1111-11",
    ie: "000.000.000.000",
    razaoSocial: "Universidade do Oeste Paulista",
    logradouro: "R. José Bongiovani, 700",
    bairro: "Cidade Universitária",
    municipio: "Presidente Prudente",
    uf: "SP",
    cep: "19050-920",
    telefone: "(18) 3229-1000",
    email: "faculdade@unoeste.edu.br",
  },
  {
    codigo: 2,
    cnpj: "22.222.222/2222-22",
    ie: "000.000.000.000",
    razaoSocial: "Universidade do Oeste Paulista",
    logradouro: "R. José Bongiovani, 700",
    bairro: "Cidade Universitária",
    municipio: "Presidente Prudente",
    uf: "SP",
    cep: "19050-920",
    telefone: "(18) 3229-1000",
    email: "faculdade@unoeste.edu.br",
  },
  {
    codigo: 3,
    cnpj: "33.333.333/3333-33",
    ie: "000.000.000.000",
    razaoSocial: "Universidade do Oeste Paulista",
    logradouro: "R. José Bongiovani, 700",
    bairro: "Cidade Universitária",
    municipio: "Presidente Prudente",
    uf: "SP",
    cep: "19050-920",
    telefone: "(18) 3229-1000",
    email: "faculdade@unoeste.edu.br",
  },
];

export const LISTA_FUNCIONARIOS = [
  {
    codigo: 1,
    cpf: "519.959.785-36",
    nome: "Márcio Santos Pauline",
    dtNascimento: "2023-01-15",
    dtAdmissao: "2023-01-15",
    dtDemissao: "2023-01-15",
    statusAtual: "Ativo",
    cargo: "Professor",
    endereco: "Rua José Pinheiro, 20",
    bairro: "Gertúlio Vargas",
    municipio: "Presidente Epitácio",
    uf: "SP",
    cep: "14001-000",
    telefone: "(18) 997784563",
    email: "marciopinheiro@aprata.com",
    usuario: "marciopinheiro",
    senha: "pinheiro123",
  },
  {
    codigo: 2,
    cpf: "472.290.568-48",
    nome: "Caio Rodrigues de Souza",
    dtNascimento: "2023-01-15",
    dtAdmissao: "2023-01-15",
    dtDemissao: "2023-01-15",
    statusAtual: "Ativo",
    cargo: "Orientador",
    endereco: "Rua José da Silva",
    bairro: "Jardim Europa",
    municipio: "Presidente Prudente",
    uf: "SP",
    cep: "19654-000",
    telefone: "(18) 981652314",
    email: "caiorodrigues@aprata.com",
    usuario: "caiorodrigues",
    senha: "caio123",
  },
  {
    codigo: 3,
    cpf: "986.295.986-62",
    nome: "Rogério Kaleb Lópes",
    dtNascimento: "2023-01-15",
    dtAdmissao: "2023-01-15",
    dtDemissao: "2023-01-15",
    statusAtual: "Inativo",
    cargo: "Administrativo",
    endereco: "Rua Napoleão Lópes, 410",
    bairro: "Jardim França",
    municipio: "Martinópolis",
    uf: "SP",
    cep: "15966-000",
    telefone: "(18) 996454493",
    email: "rogeriokaleb@aprata.com",
    usuario: "rogeriokaleb",
    senha: "kaleb123",
  },
];

export const LISTA_TURMAS = [
  {
    codigo: 1,
    periodo: "Matutino",
    anoLetivo: "2022",
    cursos: "Comunicação e Linguagem e Informática",
    dtInicio: "2022-02-12",
    dtFim: "2023-11-25",
    status: "Ativo",
    vagas: "19",
    sala: "3",
  },
  {
    codigo: 2,
    periodo: "Matutino",
    anoLetivo: "2020",
    cursos: "Técnicas em Serviços de Supermercados",
    dtInicio: "2020-02-12",
    dtFim: "2020-11-25",
    status: "Inativo",
    vagas: "29",
    sala: "1",
  },
  {
    codigo: 3,
    periodo: "Vespertino",
    anoLetivo: "2023",
    cursos: "Técnicas em Escritório e Técnico de Segurança do Trabalho",
    dtInicio: "2023-02-12",
    dtFim: "2025-11-25",
    status: "Ativo",
    vagas: "9",
    sala: "1",
  },
];
